// Code generated by ent, DO NOT EDIT.

package ent

import (
	"_schemas/ent/schema"
	"_schemas/ent/user"
	"_schemas/ent/website"
	"_schemas/ent/websiteevent"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[4].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
	websiteFields := schema.Website{}.Fields()
	_ = websiteFields
	// websiteDescCreatedAt is the schema descriptor for created_at field.
	websiteDescCreatedAt := websiteFields[3].Descriptor()
	// website.DefaultCreatedAt holds the default value on creation for the created_at field.
	website.DefaultCreatedAt = websiteDescCreatedAt.Default.(func() time.Time)
	// websiteDescUpdatedAt is the schema descriptor for updated_at field.
	websiteDescUpdatedAt := websiteFields[4].Descriptor()
	// website.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	website.DefaultUpdatedAt = websiteDescUpdatedAt.Default.(func() time.Time)
	// website.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	website.UpdateDefaultUpdatedAt = websiteDescUpdatedAt.UpdateDefault.(func() time.Time)
	// websiteDescID is the schema descriptor for id field.
	websiteDescID := websiteFields[0].Descriptor()
	// website.DefaultID holds the default value on creation for the id field.
	website.DefaultID = websiteDescID.Default.(func() uuid.UUID)
	websiteeventFields := schema.WebsiteEvent{}.Fields()
	_ = websiteeventFields
	// websiteeventDescCreatedAt is the schema descriptor for created_at field.
	websiteeventDescCreatedAt := websiteeventFields[9].Descriptor()
	// websiteevent.DefaultCreatedAt holds the default value on creation for the created_at field.
	websiteevent.DefaultCreatedAt = websiteeventDescCreatedAt.Default.(func() time.Time)
	// websiteeventDescID is the schema descriptor for id field.
	websiteeventDescID := websiteeventFields[0].Descriptor()
	// websiteevent.DefaultID holds the default value on creation for the id field.
	websiteevent.DefaultID = websiteeventDescID.Default.(func() uuid.UUID)
}
